import type { Project } from '@/types';

export const projectsData: Project[] = [
  {
    id: 'proj-1',
    title: 'Cinematic Travel Edit',
    description: 'A cinematic travel edit with smooth pacing, ambient sound design, color grading, and story-driven transitions.',
    category: 'Cinematic Edits',
    type: 'video',
    thumbnail: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    src: 'https://videos.pexels.com/video-files/2169880/2169880-hd_1280_720_30fps.mp4',
    views: 0,
    likes: 0,
    liked: false,
    comments: [],
    liveLink: 'https://www.youtube.com/',
  },
  {
    id: 'proj-2',
    title: 'Social Media Reel',
    description: 'A fast-paced vertical reel edit designed for Instagram, TikTok, and YouTube Shorts with punchy cuts and captions.',
    category: 'Reels & Shorts',
    type: 'video',
    thumbnail: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    src: 'https://videos.pexels.com/video-files/3209828/3209828-hd_1280_720_25fps.mp4',
    views: 0,
    likes: 0,
    liked: false,
    comments: [],
    liveLink: 'https://www.youtube.com/shorts/',
  },
  {
    id: 'proj-3',
    title: 'Gaming Montage',
    description: 'A high-energy gaming montage with beat-synced cuts, impact effects, speed ramps, and clean highlight timing.',
    category: 'Gaming Montages',
    type: 'video',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    src: 'https://videos.pexels.com/video-files/856956/856956-hd_1280_720_30fps.mp4',
    views: 0,
    likes: 0,
    liked: false,
    comments: [],
    liveLink: 'https://drive.google.com/',
  },
  {
    id: 'proj-4',
    title: 'Before / After Color Grade',
    description: 'A visual before-and-after editing piece focused on cinematic color correction, contrast, skin tones, and mood.',
    category: 'Before / After',
    type: 'image',
    thumbnail: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    src: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    views: 0,
    likes: 0,
    liked: false,
    comments: [],
    liveLink: 'https://drive.google.com/',
  },
  {
    id: 'proj-5',
    title: 'Brand Promo Edit',
    description: 'A short promotional edit for brands with product-focused shots, text motion, music timing, and clean transitions.',
    category: 'Cinematic Edits',
    type: 'video',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    src: 'https://videos.pexels.com/video-files/3130284/3130284-hd_1280_720_30fps.mp4',
    views: 0,
    likes: 0,
    liked: false,
    comments: [],
    liveLink: 'https://www.youtube.com/',
  },
  {
    id: 'proj-6',
    title: 'Thumbnail Design Pack',
    description: 'A collection of bold video thumbnails designed to increase clicks with strong contrast, clear subjects, and readable text.',
    category: 'Thumbnails',
    type: 'image',
    thumbnail: 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    src: 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    views: 0,
    likes: 0,
    liked: false,
    comments: [],
    liveLink: 'https://drive.google.com/',
  },
];
